version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elk
    depends_on: 
      - kafka
  logstash:
    build: logstash/
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - kibana
  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kafka:
    build: kafka/
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: "9092"
    networks: 
      - elk
  app:
    build: app/
    ports:
      - "93:8000"
    networks:
      - elk
    volumes: 
      - ../app:/var/app
    command: /bin/bash -c "uwsgi --socket :8001 --chdir /var/app/ --wsgi-file travel/wsgi.py & sleep 10 && service nginx start & nginx -g 'daemon off;'"
    depends_on: 
      - logstash

networks:
  elk:
    driver: bridge